### ISSUE TITLE
Secure Watchman secret in rs-sd-policy

### ISSUE THREAD

**Issue by swarren83** [racker/mgcp-terraform-modules#1]
The current implementation provides the Watchman secret string in plaintext.  We should use GCP KMS to obfuscate this secret.

**Comment by upodroid** [comment]
I added a note in https://github.rackspace.com/MGCP/MGCP-Terraform-Customer-Project-Skeleton that all secrets must be encrypted with KMS. It will still be visible in the state file, but it is in a private and encrypted bucket and there should be no instances with service accounts that have bucket access in the shared vpc projects.
